package danang03.STBackend.domain.employee;

public enum Skill {
    // Backend
    JAVA, SPRING_BOOT, SPRING, NODE_JS, EXPRESS, KOTLIN, C_SHARP, DOTNET, GO, RUST,
    PYTHON, DJANGO, FLASK, FASTAPI, RUBY, RUBY_ON_RAILS, PHP, LARAVEL, PERL, C, CPP,

    // Frontend
    JAVASCRIPT, TYPESCRIPT, REACT, NEXT_JS, VUE, ANGULAR, SVELTE, SOLID_JS, LIT,
    HTML, CSS, SCSS, TAILWIND_CSS, BOOTSTRAP, MATERIAL_UI,

    // Mobile
    FLUTTER, DART, REACT_NATIVE, SWIFT, OBJECTIVE_C, KOTLIN_ANDROID, JAVA_ANDROID, IONIC,

    // DevOps & Infrastructure
    DOCKER, KUBERNETES, CI_CD, JENKINS, GITHUB_ACTIONS, GITLAB_CI, ANSIBLE, TERRAFORM,
    PUPPET, CHEF, AWS, GCP, AZURE, HEROKU, DIGITAL_OCEAN, VAGRANT, OPENSHIFT,

    // Cloud Services
    AWS_LAMBDA, AWS_ECS, AWS_FARGATE, AWS_EKS, AWS_S3, AWS_CLOUDFRONT,
    AWS_RDS, AWS_DYNAMODB, AWS_API_GATEWAY, AWS_SQS, AWS_SNS,
    GCP_CLOUD_FUNCTIONS, GCP_BIGQUERY, AZURE_FUNCTIONS,

    // Databases
    MYSQL, POSTGRESQL, ORACLE_DB, SQL_SERVER, MONGODB, CASSANDRA, COUCHDB, NEO4J,
    REDIS, MEMCACHED, INFLUXDB, TIMESCALEDB, MARIA_DB, SQLITE, FIREBASE_REALTIME_DB,

    // Big Data & Streaming
    HADOOP, SPARK, KAFKA, KINESIS, FLAKE, REDSHIFT, APACHE_FLINK, APACHE_DRUID,

    // Machine Learning & AI
    TENSORFLOW, PYTORCH, SCIKIT_LEARN, KERAS, OPENCV, NLTK, TRANSFORMERS,
    HUGGING_FACE, GPT, FASTAI, DEEPSPEED, NVIDIA_CUDA,

    // Security
    JWT, OAUTH2, SAML, OPENID_CONNECT, HASHICORP_VAULT, SONARQUBE, BURP_SUITE,
    OWASP_ZAP, SELENIUM_SECURITY, CLOUD_SECURITY,

    // Networking & Protocols
    TCP_IP, UDP, HTTP, HTTPS, REST, GRAPHQL, GRPC, MQTT, WEBSOCKETS,
    WEBRTC, SOCKET_IO, DNS, TLS_SSL, SSH, FTP,

    // Testing & QA
    JUNIT, TESTNG, SELENIUM, CYPRESS, PLAYWRIGHT, APPIUM, CUCUMBER,
    POSTMAN, KARATE, JEST, MOCHA, CHAI, PYTEST,

    // CI/CD & Build Tools
    MAVEN, GRADLE, NPM, YARN, PNPM, BAZEL, BROCCOLI, GULP, WEBPACK, PARCEL,

    // Blockchain & Web3
    BITCOIN, ETHEREUM, SOLIDITY, WEB3_JS, HARDHAT, TRUFFLE, IPFS, HYPERLEDGER,

    // Game Development
    UNITY, UNREAL_ENGINE, GODOT, BLENDER, OPENGL, DIRECTX, VULKAN,

    // Miscellaneous
    GIT, SVN, MERCURIAL, AIRFLOW, KAFKA_CONNECT, PROMETHEUS, GRAFANA,
    ELK_STACK, LOGSTASH, FILEBEAT, GRAYLOG,

    // Operating Systems
    LINUX, WINDOWS_SERVER, MACOS, UNIX, BSD, DOCKER_SWARM,

    // Low-Level & Embedded
    ASM, RISC_V, ARM_CORTEX, FPGA, MICROPYTHON, ARDUINO, RASPBERRY_PI,

    // Quantum Computing
    QISKIT, MICROSOFT_QUANTUM, IBM_Q, D_WAVE;
}